on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '22.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: print secrets
      env: 
        TEST: ${{ secrets.TEST }}
      run: |
        echo "secret: $TEST"