on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: '22.x'                # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Test
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - name: print secrets
      env: 
        TEST: ${{ secrets.TEST }}
      run: |
        echo "secret: $TEST"
        echo "NODE_VERSION: $NODE_VERSION"
        echo "secret: ${#TEST}"
    - name: Run bun
      run: |
        bun install                    # Install dependencies